import psycopg2
import os
from dotenv import load_dotenv
from datetime import datetime

def run_etl():
    """
    Ejecuta el proceso ETL para migrar datos de la BD transaccional a la BD analítica.
    """
    conn_source = None
    cursor_source = None
    conn_target = None
    cursor_target = None

    try:
        # --- Configuración y Conexión a Bases de Datos ---
        dotenv_path = os.path.join(os.path.dirname(__file__), '..', 'Credenciales_ENV', '.env')
        load_dotenv(dotenv_path)

        # Conexión a la Base de Datos de Origen (Transaccional)
        print("Conectando a la base de datos de origen...")
        conn_source = psycopg2.connect(
            host=os.getenv("DB_HOST"),
            port=os.getenv("DB_PORT"),
            dbname=os.getenv("DB_NAME_SOURCE"),
            user=os.getenv("DB_USER"),
            password=os.getenv("DB_PASSWORD")
        )
        cursor_source = conn_source.cursor()
        print("Conexión a la BD de origen establecida.")

        # Conexión a la Base de Datos de Destino (Analítica/Data Warehouse)
        print("Conectando a la base de datos de destino...")
        conn_target = psycopg2.connect(
            host=os.getenv("DB_HOST"),
            port=os.getenv("DB_PORT"),
            dbname=os.getenv("DB_NAME_TARGET"),
            user=os.getenv("DB_USER"),
            password=os.getenv("DB_PASSWORD")
        )
        cursor_target = conn_target.cursor()
        print("Conexión a la BD de destino establecida.")

        # --- FASE 1: Drop y Creación de Esquema en BD Destino ---
        print("\n--- Fase 1: Limpiando y Creando el Esquema en la BD de Destino ---")
        target_schema_sql = """
        -- Eliminar tablas en orden inverso de dependencia para evitar errores de FK
        DROP TABLE IF EXISTS "Hechos_Ordenes" CASCADE;
        DROP TABLE IF EXISTS "Reservas" CASCADE; -- Renombrada a dimensión en destino
        DROP TABLE IF EXISTS "Mesas" CASCADE;
        DROP TABLE IF EXISTS "Platillos" CASCADE;
        DROP TABLE IF EXISTS "MetodoPago" CASCADE;
        DROP TABLE IF EXISTS "EstadoReserva" CASCADE;
        DROP TABLE IF EXISTS "Clientes" CASCADE;

        -- Crear tablas del esquema de destino
        CREATE TABLE "Clientes" (
          "Id_cliente" int PRIMARY KEY,
          "Nombre" text,
          "Telefono" varchar,
          "Correo" text
        );

        CREATE TABLE "Mesas" (
          "N_Mesa" int PRIMARY KEY,
          "Capacidad" int,
          "Ubicacion" varchar -- Cambiado de int a varchar
        );

        CREATE TABLE "Reservas" ( -- Ahora es una tabla de dimensión para la tabla de hechos
          "Id_reserva" int PRIMARY KEY,
          "Fecha" date,
          "Cantidad" int
        );

        CREATE TABLE "Platillos" (
          "Id_platillo" int PRIMARY KEY,
          "Nombre" varchar,
          "Precio" int,
          "Descripcion" text
        );

        CREATE TABLE "MetodoPago" (
          "Id_metodo" int PRIMARY KEY,
          "Metodo" varchar
        );

        CREATE TABLE "EstadoReserva" (
          "Id_estado" int PRIMARY KEY,
          "Estado" varchar
        );

        CREATE TABLE "Hechos_Ordenes" (
          "Id_orden" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "Fecha" date,
          "Id_cliente" int,
          "N_Mesa" int,
          "Id_reserva" int,
          "Id_platillo" int,
          "Cantidad" int,
          "Precio_unitario" int,
          "Total" int,
          "Id_metodo" int,
          "Id_estado" int
        );

        -- Añadir claves foráneas
        ALTER TABLE "Hechos_Ordenes" ADD FOREIGN KEY ("Id_cliente") REFERENCES "Clientes" ("Id_cliente");
        ALTER TABLE "Hechos_Ordenes" ADD FOREIGN KEY ("N_Mesa") REFERENCES "Mesas" ("N_Mesa");
        ALTER TABLE "Hechos_Ordenes" ADD FOREIGN KEY ("Id_reserva") REFERENCES "Reservas" ("Id_reserva");
        ALTER TABLE "Hechos_Ordenes" ADD FOREIGN KEY ("Id_platillo") REFERENCES "Platillos" ("Id_platillo");
        ALTER TABLE "Hechos_Ordenes" ADD FOREIGN KEY ("Id_metodo") REFERENCES "MetodoPago" ("Id_metodo");
        ALTER TABLE "Hechos_Ordenes" ADD FOREIGN KEY ("Id_estado") REFERENCES "EstadoReserva" ("Id_estado");
        """
        cursor_target.execute(target_schema_sql)
        conn_target.commit()
        print("Esquema de destino creado/limpiado exitosamente.")

        # --- FASE 2: Extracción y Carga de Tablas de Dimensión ---
        print("\n--- Fase 2: Cargando Tablas de Dimensión ---")

        # Dimensión: Clientes
        print("Cargando dimensión Clientes...")
        cursor_source.execute('SELECT "Id_cliente", "Nombre_cliente", "Telefono_cliente", "Correo_cliente" FROM "Clientes"')
        clientes_data = cursor_source.fetchall()
        for row in clientes_data:
            cursor_target.execute(
                '''INSERT INTO "Clientes" ("Id_cliente", "Nombre", "Telefono", "Correo") VALUES (%s, %s, %s, %s)''',
                row
            )
        conn_target.commit()
        print(f"Cargados {len(clientes_data)} clientes.")

        # Dimensión: Platillos
        print("Cargando dimensión Platillos...")
        cursor_source.execute('SELECT "Id_platillo", "Nombre", "Precio", "Descripcion" FROM "Platillos"')
        platillos_data = cursor_source.fetchall()
        for row in platillos_data:
            cursor_target.execute(
                '''INSERT INTO "Platillos" ("Id_platillo", "Nombre", "Precio", "Descripcion") VALUES (%s, %s, %s, %s)''',
                row
            )
        conn_target.commit()
        print(f"Cargados {len(platillos_data)} platillos.")

        # Dimensión: MetodoPago
        print("Cargando dimensión MetodoPago...")
        cursor_source.execute('SELECT "Id_metodo", "Metodo" FROM "MetodoPago"')
        metodo_pago_data = cursor_source.fetchall()
        for row in metodo_pago_data:
            cursor_target.execute(
                '''INSERT INTO "MetodoPago" ("Id_metodo", "Metodo") VALUES (%s, %s)''',
                row
            )
        conn_target.commit()
        print(f"Cargados {len(metodo_pago_data)} métodos de pago.")

        # Dimensión: EstadoReserva
        print("Cargando dimensión EstadoReserva...")
        cursor_source.execute('SELECT "Id_estado", "Estado" FROM "EstadoReserva"')
        estado_reserva_data = cursor_source.fetchall()
        for row in estado_reserva_data:
            cursor_target.execute(
                '''INSERT INTO "EstadoReserva" ("Id_estado", "Estado") VALUES (%s, %s)''',
                row
            )
        conn_target.commit()
        print(f"Cargados {len(estado_reserva_data)} estados de reserva.")

        # Dimensión: Reservas (transformación de nombre de columna)
        print("Cargando dimensión Reservas...")
        cursor_source.execute('SELECT "Id_reserva", "Fecha", "Cantidad_personas" FROM "Reservas"')
        reservas_data = cursor_source.fetchall()
        for row in reservas_data:
            cursor_target.execute(
                '''INSERT INTO "Reservas" ("Id_reserva", "Fecha", "Cantidad") VALUES (%s, %s, %s)''',
                row
            )
        conn_target.commit()
        print(f"Cargadas {len(reservas_data)} reservas como dimensión.")

        # Dimensión: Mesas (transformación de Ubicacion de INT a VARCHAR)
        print("Cargando dimensión Mesas...")
        cursor_source.execute('''
            SELECT M."N_Mesa", M."Capacidad", U."Ubicacion_local"
            FROM "Mesas" M
            JOIN "Ubicaciones" U ON M."Ubicacion" = U."Id_ubicacion"
        ''')
        mesas_data = cursor_source.fetchall()
        for row in mesas_data:
            cursor_target.execute(
                '''INSERT INTO "Mesas" ("N_Mesa", "Capacidad", "Ubicacion") VALUES (%s, %s, %s)''',
                row
            )
        conn_target.commit()
        print(f"Cargadas {len(mesas_data)} mesas (con ubicación transformada).")


        # --- FASE 3: Extracción, Transformación y Carga de Tabla de Hechos ---
        print("\n--- Fase 3: Cargando Tabla de Hechos (Hechos_Ordenes) ---")

        # Consulta compleja para extraer y transformar los datos para la tabla de hechos
        # Une Pedidos, Ventas, Platillos y busca la Reserva, Cliente y Estado_Reserva asociados.
        # Utiliza un CTE (Common Table Expression) para manejar la posible duplicidad de reservas
        # por mesa y fecha, seleccionando la reserva con el Id_reserva más bajo.
        fact_orders_sql = """
        WITH RankedReservas AS (
            SELECT
                "Id_reserva",
                "Id_cliente",
                "Id_mesa",
                "Fecha",
                "Id_estado",
                ROW_NUMBER() OVER (PARTITION BY "Id_mesa", "Fecha" ORDER BY "Id_reserva") as rn
            FROM "Reservas"
        )
        SELECT
            V."Fecha" AS Fecha,
            RR."Id_cliente" AS Id_cliente,
            P."Id_mesa" AS N_Mesa,
            RR."Id_reserva" AS Id_reserva,
            P."Id_platillo" AS Id_platillo,
            P."Cantidad_platillo" AS Cantidad,
            PL."Precio" AS Precio_unitario,
            P."Subtotal" AS Total,
            V."Id_metodo" AS Id_metodo,
            RR."Id_estado" AS Id_estado
        FROM
            "Pedidos" P
        JOIN
            "Ventas" V ON P."Id_venta" = V."Id_ventas"
        JOIN
            "Platillos" PL ON P."Id_platillo" = PL."Id_platillo"
        LEFT JOIN -- LEFT JOIN porque no todos los pedidos/ventas tienen una reserva directa
            RankedReservas RR ON P."Id_mesa" = RR."Id_mesa" AND V."Fecha" = RR."Fecha" AND RR.rn = 1;
        """
        cursor_source.execute(fact_orders_sql)
        hechos_ordenes_data = cursor_source.fetchall()

        # Insertar los datos en la tabla de hechos de destino
        for row in hechos_ordenes_data:
            cursor_target.execute(
                '''INSERT INTO "Hechos_Ordenes"
                   ("Fecha", "Id_cliente", "N_Mesa", "Id_reserva", "Id_platillo",
                    "Cantidad", "Precio_unitario", "Total", "Id_metodo", "Id_estado")
                   VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)''',
                row # La columna Id_orden es GENERATED BY DEFAULT AS IDENTITY
            )
        conn_target.commit()
        print(f"Cargados {len(hechos_ordenes_data)} registros en Hechos_Ordenes.")

        print("\n¡Proceso ETL completado exitosamente!")

    except psycopg2.Error as e:
        print(f"Error de base de datos durante el ETL: {e}")
        # Realiza rollback en ambas conexiones si hay un error
        if conn_source:
            conn_source.rollback()
        if conn_target:
            conn_target.rollback()
    except Exception as e:
        print(f"Ocurrió un error inesperado durante el ETL: {e}")
        if conn_source:
            conn_source.rollback()
        if conn_target:
            conn_target.rollback()
    finally:
        # --- Cierre de Conexiones ---
        print("\nCerrando conexiones a las bases de datos...")
        if cursor_source:
            cursor_source.close()
        if conn_source:
            conn_source.close()
        if cursor_target:
            cursor_target.close()
        if conn_target:
            conn_target.close()
        print("Conexiones cerradas.")

if __name__ == "__main__":
    run_etl()

