CREATE TABLE "Hechos_Ordenes" (
  "Id_orden" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Fecha" date,
  "Id_cliente" int,
  "N_Mesa" int,
  "Id_reserva" int,
  "Id_platillo" int,
  "Cantidad" int,
  "Precio_unitario" int,
  "Total" int,
  "Id_metodo" int,
  "Id_estado" int
);

CREATE TABLE "Clientes" (
  "Id_cliente" int PRIMARY KEY,
  "Nombre" text,
  "Telefono" varchar,
  "Correo" text
);

CREATE TABLE "Mesas" (
  "N_Mesa" int PRIMARY KEY,
  "Capacidad" int,
  "Ubicacion" varchar
);

CREATE TABLE "Reservas" (
  "Id_reserva" int PRIMARY KEY,
  "Fecha" date,
  "Cantidad" int
);

CREATE TABLE "Platillos" (
  "Id_platillo" int PRIMARY KEY,
  "Nombre" varchar,
  "Precio" int,
  "Descripcion" text
);

CREATE TABLE "MetodoPago" (
  "Id_metodo" int PRIMARY KEY,
  "Metodo" varchar
);

CREATE TABLE "EstadoReserva" (
  "Id_estado" int PRIMARY KEY,
  "Estado" varchar
);

ALTER TABLE "Hechos_Ordenes" ADD FOREIGN KEY ("Id_cliente") REFERENCES "Clientes" ("Id_cliente");

ALTER TABLE "Hechos_Ordenes" ADD FOREIGN KEY ("N_Mesa") REFERENCES "Mesas" ("N_Mesa");

ALTER TABLE "Hechos_Ordenes" ADD FOREIGN KEY ("Id_reserva") REFERENCES "Reservas" ("Id_reserva");

ALTER TABLE "Hechos_Ordenes" ADD FOREIGN KEY ("Id_platillo") REFERENCES "Platillos" ("Id_platillo");

ALTER TABLE "Hechos_Ordenes" ADD FOREIGN KEY ("Id_metodo") REFERENCES "MetodoPago" ("Id_metodo");

ALTER TABLE "Hechos_Ordenes" ADD FOREIGN KEY ("Id_estado") REFERENCES "EstadoReserva" ("Id_estado");
